MovieWeb/MovieWeb/Models/ErrorViewModel.cs
namespace MovieWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieWeb/MovieWeb/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace MovieWeb.Models
{
    public class Movie
    {
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage = "Movie tilte cannot blank")]
        public string title { get; set; }
        public string description { get; set; }
        public string imgUrl { get; set; }
        [Required, Range(0.0f, 10.0f)]
        public float rating { get; set; }
    }
}

MovieWeb/MovieWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieWeb/MovieWeb/Controllers/WebHomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Data;
using MovieWeb.Models;
using System.Net;

namespace MovieWeb.Controllers
{
    public class WebHomeController : Controller
    {
        private readonly ApplicationDBContext _db;
        public WebHomeController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Movie> movies = _db.Movies;
            return View(movies);
        }

        // GET Method for showing Form webpage without this it will be unable to open the create form page
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _db.Movies.Add(movie);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _db.Movies.Update(movie);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        public IActionResult Delete(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return NotFound();
            }
            _db.Movies.Remove(movie);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MovieWeb/MovieWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieWeb/MovieWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieWeb</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebHome" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebHome" asp-action="Create">Create Review</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Jirakit Jarusiripipat
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieWeb/MovieWeb/Views/WebHome/Create.cshtml
@model Movie

@{
    ViewData["Title"] = "Create Review";
}
<h1 class="text-center">Create Review</h1>
<form method="post" asp-controller="WebHome" asp-action="Create">
    <div class ="from-group">
        <label asp-for="title">Title</label>
        <input type="text" asp-for="title" class="form-control"/>
        <span asp-validation-for="title" class="text-danger"></span>
    </div>
    <div class="from-group">
        <label asp-for="description">Description</label>
        <input type="text" asp-for="description" class="form-control"/>
    </div>
    <div class="from-group">
        <label asp-for="imgUrl">Image URL</label>
        <input type="url" asp-for="imgUrl" class="form-control"/>
        <span asp-validation-for="imgUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="rating">Rating</label>
        <input type="number" step=".01" asp-for="rating" class="form-control"/>
        <span asp-validation-for="rating" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary my-2">Create Review</button>
</form>

MovieWeb/MovieWeb/Views/WebHome/Edit.cshtml
@model Movie

@{
    ViewData["Title"] = "Edit Review";
}
<h1 class="text-center">Edit Review</h1>
<form method="post" asp-controller="WebHome" asp-action="Edit">
    <div class="from-group">
        <label asp-for="title">Title</label>
        <input type="text" asp-for="title" class="form-control" />
        <span asp-validation-for="title" class="text-danger"></span>
    </div>
    <div class="from-group">
        <label asp-for="description">Description</label>
        <input type="text" asp-for="description" class="form-control" />
    </div>
    <div class="from-group">
        <label asp-for="imgUrl">Image URL</label>
        <input type="url" asp-for="imgUrl" class="form-control" />
        <span asp-validation-for="imgUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="rating">Rating</label>
        <input type="number" step=".01" asp-for="rating" class="form-control" />
        <span asp-validation-for="rating" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary my-2">Edit Review</button>
</form>

MovieWeb/MovieWeb/Views/WebHome/Index.cshtml
@model IEnumerable<MovieWeb.Models.Movie>
@{
    ViewData["Title"] = "Home";
}

@if (Model.Count() > 0)
{
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Image</th>
                <th>Movie ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Rating</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr>
                    <td><img src="@movie.imgUrl" width="180" height="200"></td>
                    <td>@movie.id</td>
                    <td>@movie.title</td>
                    <td>@movie.description</td>
                    <td>@movie.rating/10</td>
                    <td><a class="btn btn-warning" asp-controller="WebHome" asp-action="Edit" asp-route-id="@movie.id">Edit</a></td>
                    <td><a class="btn btn-danger" asp-controller="WebHome" asp-action="Delete" asp-route-id="@movie.id" onclick="return confirm('Do you want to delete @movie.title?')">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-secondary">No Movie Data</div>
}